import { Image } from "./Image/Image";

export const TypeList = [
  { Image: Image.Type_Image_1, label: "Sculptures & Artifacts" },
  { Image: Image.Type_Image_2, label: "Vases" },
  { Image: Image.Type_Image_3, label: "Wall Art/Clocks" },
  { Image: Image.Type_Image_4, label: "Planters" },
  { Image: Image.Type_Image_5, label: "Wall Paintings" },
  { Image: Image.Type_Image_6, label: "Candle & Candle Holders" },
];

export const ProductList = [
  // Sculptures & Artifacts
  {
    id: "item1",
    image: Image.Type_Image_1,
    category: "Sculptures & Artifacts",
    name: "Abstract Bronze Figure",
    price: 207500.0,
    description:
      "A modern abstract bronze sculpture, hand-crafted by an emerging artist. Perfect for living room or office decor. Material: Bronze, 12 inches tall.",
    stock: 5,
    rating: 4.8,
    dimensions: "12x6x6 inches",
    material: "Bronze",
    discount: 0,
  },
  {
    id: "item2",
    image: Image.Type_Image_1,
    category: "Sculptures & Artifacts",
    name: "Antikythera Mechanism Replica",
    price: 9877.0,
    description:
      "Handmade alabaster reproduction of the ancient Greek Antikythera Mechanism, bronze effect finish. Ideal for history enthusiasts. Dimensions: 7.8 x 5.5 inches.",
    stock: 20,
    rating: 4.5,
    dimensions: "7.8x5.5x3 inches",
    material: "Alabaster",
    discount: 10,
  },
  {
    id: "item3",
    image: Image.Type_Image_1,
    category: "Sculptures & Artifacts",
    name: "Marble Aphrodite Bust",
    price: 9130.0,
    описание:
      "Классический греческий бюст Афродиты, богини любви, выполненный из мрамора. Реплика музейного качества, высота 10 дюймов.",
    stock: 15,
    rating: 4.7,
    dimensions: "10x5x5 inches",
    material: "Marble",
    discount: 0,
  },
  {
    id: "item4",
    image: Image.Type_Image_1,
    category: "Sculptures & Artifacts",
    name: "Wooden Tribal Mask",
    price: 7055.0,
    description:
      "Hand-carved African tribal mask made from teak wood, featuring intricate patterns. Wall-mountable, 15 inches tall.",
    stock: 30,
    rating: 4.3,
    dimensions: "15x8x3 inches",
    material: "Teak Wood",
    discount: 5,
  },
  {
    id: "item5",
    image: Image.Type_Image_1,
    category: "Sculptures & Artifacts",
    name: "Glass Kinetic Sculpture",
    price: 37350.0,
    description:
      "Contemporary glass sculpture with moving elements, ideal for modern interiors. Material: Blown glass, 18 inches tall.",
    stock: 8,
    rating: 4.9,
    dimensions: "18x10x10 inches",
    material: "Blown Glass",
    discount: 0,
  },
  // Vases
  {
    id: "item6",
    image: Image.Type_Image_2,
    category: "Vases",
    name: "Ceramic Blue Wave Vase",
    price: 3735.0,
    description:
      "Hand-painted ceramic vase with ocean-inspired design. Suitable for fresh or dried flowers. Height: 8 inches.",
    stock: 50,
    rating: 4.4,
    dimensions: "8x5x5 inches",
    material: "Ceramic",
    discount: 15,
  },
  {
    id: "item7",
    image: Image.Type_Image_2,
    category: "Vases",
    name: "Marble Grecian Urn",
    price: 7469.17,
    description:
      "Elegant marble vase inspired by ancient Greek pottery. Ideal for minimalist decor. Height: 12 inches.",
    stock: 25,
    rating: 4.6,
    dimensions: "12x6x6 inches",
    material: "Marble",
    discount: 0,
  },
  {
    id: "item8",
    image: Image.Type_Image_2,
    category: "Vases",
    name: "Matte Black Ceramic Vase",
    price: 3319.17,
    description:
      "Sleek matte black ceramic vase, perfect for modern decor. Height: 10 inches, suitable for tall stems.",
    stock: 40,
    rating: 4.5,
    dimensions: "10x4x4 inches",
    material: "Ceramic",
    discount: 10,
  },
  {
    id: "item9",
    image: Image.Type_Image_2,
    category: "Vases",
    name: "Hand-Blown Glass Vase",
    price: 5395.0,
    description:
      "Artisan hand-blown glass vase with iridescent finish. Unique shape, 9 inches tall.",
    stock: 15,
    rating: 4.8,
    dimensions: "9x5x5 inches",
    material: "Glass",
    discount: 0,
  },
  // Wall Art/Clocks
  {
    id: "item10",
    image: Image.Type_Image_3,
    category: "Wall Art/Clocks",
    name: "Abstract Canvas Print",
    price: 6639.17,
    description:
      "Vibrant abstract wall art on stretched canvas, ready to hang. Dimensions: 24 x 36 inches.",
    stock: 35,
    rating: 4.4,
    dimensions: "24x36x1 inches",
    material: "Canvas",
    discount: 5,
  },
  {
    id: "item11",
    image: Image.Type_Image_3,
    category: "Wall Art/Clocks",
    name: "Vintage Wall Clock",
    price: 4938.5,
    description:
      "Retro-style wall clock with silent mechanism, wooden frame. Diameter: 14 inches.",
    stock: 20,
    rating: 4.6,
    dimensions: "14x14x2 inches",
    material: "Wood",
    discount: 0,
  },
  {
    id: "item12",
    image: Image.Type_Image_3,
    category: "Wall Art/Clocks",
    name: "Minimalist Metal Wall Art",
    price: 8217.0,
    description:
      "Laser-cut metal wall art with geometric design, black finish. Dimensions: 30 x 20 inches.",
    stock: 10,
    rating: 4.7,
    dimensions: "30x20x1 inches",
    material: "Metal",
    discount: 0,
  },
  {
    id: "item13",
    image: Image.Type_Image_3,
    category: "Wall Art/Clocks",
    name: "Industrial Gear Wall Clock",
    price: 6225.0,
    description:
      "Large industrial-style wall clock with exposed gears, metal frame. Diameter: 20 inches.",
    stock: 15,
    rating: 4.5,
    dimensions: "20x20x3 inches",
    material: "Metal",
    discount: 10,
  },
  // Planters
  {
    id: "item14",
    image: Image.Type_Image_4,
    category: "Planters",
    name: "Terracotta Herb Planter",
    price: 2489.17,
    description:
      "Rustic terracotta planter for herbs or small plants. Includes drainage hole. Dimensions: 6 x 6 inches.",
    stock: 60,
    rating: 4.3,
    dimensions: "6x6x6 inches",
    material: "Terracotta",
    discount: 20,
  },
  {
    id: "item15",
    image: Image.Type_Image_4,
    category: "Planters",
    name: "Modern Concrete Planter",
    price: 4149.17,
    description:
      "Sleek concrete planter with geometric design, ideal for succulents. Dimensions: 8 x 8 inches.",
    stock: 30,
    rating: 4.6,
    dimensions: "8x8x8 inches",
    material: "Concrete",
    discount: 0,
  },
  {
    id: "item16",
    image: Image.Type_Image_4,
    category: "Planters",
    name: "Hanging Ceramic Planter",
    price: 2904.17,
    description:
      "White ceramic hanging planter with macramé rope, perfect for trailing plants. Diameter: 5 inches.",
    stock: 25,
    rating: 4.4,
    dimensions: "5x5x5 inches",
    material: "Ceramic",
    discount: 10,
  },
  {
    id: "item17",
    image: Image.Type_Image_4,
    category: "Planters",
    name: "Brass Inlaid Wooden Planter",
    price: 4979.17,
    description:
      "Rectangular wooden planter with brass inlay, ideal for indoor herbs. Dimensions: 12 x 4 inches.",
    stock: 20,
    rating: 4.7,
    dimensions: "12x4x4 inches",
    material: "Wood",
    discount: 0,
  },
  // Wall Paintings
  {
    id: "item18",
    image: Image.Type_Image_5,
    category: "Wall Paintings",
    name: "Floral Watercolor Painting",
    price: 8217.0,
    description:
      "Original watercolor painting of wildflowers, framed. Dimensions: 16 x 20 inches.",
    stock: 10,
    rating: 4.8,
    dimensions: "16x20x1 inches",
    material: "Watercolor",
    discount: 5,
  },
  {
    id: "item19",
    image: Image.Type_Image_5,
    category: "Wall Paintings",
    name: "Cityscape Oil Painting",
    price: 12449.17,
    description:
      "Hand-painted cityscape in oils, vibrant colors, framed. Dimensions: 20 x 24 inches.",
    stock: 8,
    rating: 4.9,
    dimensions: "20x24x1 inches",
    material: "Oil Paint",
    discount: 0,
  },
  {
    id: "item20",
    image: Image.Type_Image_5,
    category: "Wall Paintings",
    name: "Abstract Acrylic Painting",
    price: 10789.17,
    description:
      "Bold abstract painting in acrylics, unframed, ready to hang. Dimensions: 24 x 24 inches.",
    stock: 12,
    rating: 4.6,
    dimensions: "24x24x1 inches",
    material: "Acrylic",
    discount: 10,
  },
  {
    id: "item21",
    image: Image.Type_Image_5,
    category: "Wall Paintings",
    name: "Landscape Oil Painting",
    price: 14949.17,
    description:
      "Traditional oil painting of a serene landscape, framed in wood. Dimensions: 30 x 20 inches.",
    stock: 5,
    rating: 4.8,
    dimensions: "30x20x1 inches",
    material: "Oil Paint",
    discount: 0,
  },
  // Candle & Candle Holders
  {
    id: "item22",
    image: Image.Type_Image_6,
    category: "Candle & Candle Holders",
    name: "Marble Tealight Holder",
    price: 1659.17,
    description:
      "Elegant white marble tealight holder, fits standard tealights. Dimensions: 3 x 3 inches.",
    stock: 50,
    rating: 4.3,
    dimensions: "3x3x3 inches",
    material: "Marble",
    discount: 15,
  },
  {
    id: "item23",
    image: Image.Type_Image_6,
    category: "Candle & Candle Holders",
    name: "Scented Soy Candle",
    price: 2074.17,
    description:
      "Hand-poured lavender-scented soy candle in glass jar, 40-hour burn time. Volume: 8 oz.",
    stock: 40,
    rating: 4.5,
    dimensions: "3x3x4 inches",
    material: "Soy Wax",
    discount: 10,
  },
  {
    id: "item24",
    image: Image.Type_Image_6,
    category: "Candle & Candle Holders",
    name: "Brass Pillar Candle Holder",
    price: 2489.17,
    description:
      "Polished brass candle holder for pillar candles, vintage-inspired design. Height: 6 inches.",
    stock: 30,
    rating: 4.6,
    dimensions: "4x4x6 inches",
    material: "Brass",
    discount: 0,
  },
  {
    id: "item25",
    image: Image.Type_Image_6,
    category: "Candle & Candle Holders",
    name: "Vanilla Beeswax Candle",
    price: 1867.5,
    description:
      "Natural beeswax candle with vanilla scent, eco-friendly, 30-hour burn time. Volume: 6 oz.",
    stock: 35,
    rating: 4.4,
    dimensions: "3x3x3 inches",
    material: "Beeswax",
    discount: 5,
  },
];
